# -*- coding: utf-8 -*-
"""API.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QdFOepPhm3jYKZfpF9JIxG0i6Wh_P6f6
"""

pip install streamlit

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier

st.title('Uber pickups in NYC')

!streamlit run API.py